# Arquivo de configuração do Netlify (netlify.toml)

[build]
  publish = "public"
  command = "npm install && npm run build:css"

# Configurações de Cabeçalhos HTTP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

    # Política de Segurança de Conteúdo (CSP) - Otimizada para Produção
    # - Removido Tailwind CDN pois o CSS agora é compilado dinamicamente.
    # - Mantido 'unsafe-inline' para script-src e style-src (necessário para Gtag inline).
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://googleads.g.doubleclick.net https://pagead2.googlesyndication.com https://*.trustindex.io https://trustindex.io https://*.elfsight.com https://elfsight.com https://*.elfsightcdn.com https://elfsightcdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.trustindex.io https://trustindex.io https://*.elfsight.com https://elfsight.com https://*.elfsightcdn.com https://elfsightcdn.com; font-src 'self' https://fonts.gstatic.com https://*.trustindex.io; connect-src 'self' https://www.google-analytics.com https://stats.g.doubleclick.net https://googleads.g.doubleclick.net https://www.google.com https://region1.google-analytics.com https://*.trustindex.io https://trustindex.io https://*.elfsight.com https://elfsight.com https://*.elfsightcdn.com https://elfsightcdn.com; img-src 'self' data: https://www.google.com https://www.google.com.br https://www.google.al *.google.com *.gstatic.com https://*.trustindex.io https://trustindex.io https://lh3.googleusercontent.com https://geougc-cs https://*.elfsight.com https://elfsight.com https://*.elfsightcdn.com https://elfsightcdn.com; frame-src 'self' https://www.googletagmanager.com https://*.trustindex.io https://trustindex.io https://*.elfsight.com https://elfsight.com https://*.elfsightcdn.com https://elfsightcdn.com;"


    # Força HTTPS (HSTS) - Mantido max-age de 6 meses.
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"

    Cross-Origin-Opener-Policy = "same-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # require-trusted-types-for = "'script';" # Mantido comentado

