# Arquivo de configuração do Netlify (netlify.toml)

# Configurações de Cabeçalhos HTTP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

    # Política de Segurança de Conteúdo (CSP) - AJUSTADA
    # - Adicionado 'region1.google-analytics.com' ao connect-src para corrigir erro do console.
    # - Mantido 'unsafe-inline' para script-src e style-src (necessário para Tailwind CDN e Gtag inline).
    # - Mantidos domínios do Google Analytics/Ads e fontes.
    # - Mantidos domínios do Google em img-src.
    # - Adicionado googletagmanager.com ao frame-src.
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://cdn.tailwindcss.com https://googleads.g.doubleclick.net https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://www.google-analytics.com https://stats.g.doubleclick.net https://googleads.g.doubleclick.net https://www.google.com https://region1.google-analytics.com; img-src 'self' data: https://www.google.com https://www.google.com.br *.google.com *.gstatic.com; frame-src 'self' https://www.googletagmanager.com;"

    # Força HTTPS (HSTS) - Mantido max-age de 6 meses.
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"

    Cross-Origin-Opener-Policy = "same-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # require-trusted-types-for = "'script';" # Mantido comentado
